# Generated by Django 2.1.3 on 2018-12-17 08:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='main_photo',
            field=models.ImageField(default='default.svg', upload_to='partners_profile'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
