# Generated by Django 2.1.5 on 2019-01-21 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='list_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), blank=True, null=True, size=None),
        ),
    ]
