# Generated by Django 2.1.3 on 2019-01-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190105_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Select Gender', max_length=20),
        ),
    ]
