# Generated by Django 2.1.3 on 2019-01-04 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('pub_date', models.DateField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
