cities = {
    'port said': 'Port said',
    'giza': 'Giza',
    'north sinai': 'North sinai',
    'luxor': 'Luxor',
    'assyout': 'Assyout',
    'el beheira': 'El beheira',
    'el fayoum': 'El fayoum',
    'damietta': 'Damietta',
    'el menia': 'El menia',
    'alexandria': 'Alexandria',
    'el monofeya': 'El monofeya',
    'ismaileya': 'Ismaileya',
    'el dakahleya': 'El dakahleya',
    'aswan': 'Aswan',
    'north coast': 'North coast',
    'sharm el sheikh': 'Sharm el sheikh',
    'kafr el sheikh': 'Kafr el sheikh',
    'hurghada': 'Hurghada',
    'el sharkeya': 'El sharkeya',
    'cairo': 'Cairo',
    'kaliobeya': 'Kaliobeya',
    'qena': 'Qena',
    'el gouna': 'El gouna',
    'suez': 'Suez',
    'benisuef': 'Benisuef',
    'el gharbeya': 'El gharbeya',
}


districts = {
    'el koba el gadida': 'El koba el gadida',
    'minuf': 'Minuf',
    'el seyouf': 'El seyouf',
    'el sawah': 'El sawah',
    'faisal': 'Faisal',
    'el herafeyeen': 'El herafeyeen',
    'kutour': 'Kutour',
    'el attarin': 'El attarin',
    'lazoughly': 'Lazoughly',
    'wabour el mayah': 'Wabour el mayah',
    'el sherouk city': 'El sherouk city',
    'abou rawash': 'Abou rawash',
    'el asafra bahary': 'El asafra bahary',
    'san stefano': 'San stefano',
    'hamamat el kobba': 'Hamamat el kobba',
    'abou el nomrous': 'Abou el nomrous',
    'abi al abbas': 'Abi al abbas',
    'saba pasha': 'Saba pasha',
    'ard el lewaa': 'Ard el lewaa',
    'el helmeya el gedidah': 'El helmeya el gedidah',
    'sidi abdel rahman': 'Sidi abdel rahman',
    'abbasseya': 'Abbasseya',
    'cleopatra al mahata': 'Cleopatra al mahata',
    'banha': 'Banha',
    'esna': 'Esna',
    'naama bay': 'Naama bay',
    'moharram bey': 'Moharram bey',
    'el roda': 'El roda',
    'semouha': 'Semouha',
    'el nozha el gadida': 'El nozha el gadida',
    'wadi houf': 'Wadi houf',
    'mallawi': 'Mallawi',
    'dar el salam': 'Dar el salam',
    'garden bay': 'Garden bay',
    'ghebrial': 'Ghebrial',
    'el mansoura': 'El mansoura',
    'alex. matrouh desert rd.': 'Alex. matrouh desert rd.',
    'faggala': 'Faggala',
    'el bassateen': 'El bassateen',
    'wayli': 'Wayli',
    'sporting': 'Sporting',
    'takseem 2': 'Takseem 2',
    'el mahalla el kobra': 'El mahalla el kobra',
    'el hadara el gadida': 'El hadara el gadida',
    'el amireya': 'El amireya',
    'el sofy': 'El sofy',
    'sidi beshr': 'Sidi beshr',
    'cairo alex desert rd.': 'Cairo alex desert rd.',
    'banha el gadida': 'Banha el gadida',
    'roushdy': 'Roushdy',
    'suez district': 'Suez district',
    'bigam': 'Bigam',
    'dokki': 'Dokki',
    'gharb district': 'Gharb district',
    'camp shizar': 'Camp shizar',
    'mokattam': 'Mokattam',
    'garden city': 'Garden city',
    'sidi beshr bahary': 'Sidi beshr bahary',
    'el gomrok': 'El gomrok',
    'shebein el kawm': 'Shebein el kawm',
    'el hadara': 'El hadara',
    'ramlet boulak': 'Ramlet boulak',
    'el fustat': 'El fustat',
    'misr el kadima': 'Misr el kadima',
    'cleopatra': 'Cleopatra',
    'el salam city': 'El salam city',
    'sidi beshr kebly': 'Sidi beshr kebly',
    'ibshaway': 'Ibshaway',
    'fleming': 'Fleming',
    'el quseyah': 'El quseyah',
    'al rehab city': 'Al rehab city',
    'bein el sarayat': 'Bein el sarayat',
    'abou youssef': 'Abou youssef',
    'abou zaabal': 'Abou zaabal',
    'el arbeen': 'El arbeen',
    'kaha': 'Kaha',
    'as-santah': 'As-santah',
    'el zawia el hamra': 'El zawia el hamra',
    'el shark district': 'El shark district',
    'el seyouf shamaa': 'El seyouf shamaa',
    'bahary': 'Bahary',
    'etay el barod': 'Etay el barod',
    'el kalag': 'El kalag',
    'dayr mawas': 'Dayr mawas',
    'el saah square': 'El saah square',
    'el zaher': 'El zaher',
    'disuq': 'Disuq',
    'alex. cairo desert rd.': 'Alex. cairo desert rd.',
    'quwasnah': 'Quwasnah',
    'el nemsa': 'El nemsa',
    'abou hammad': 'Abou hammad',
    'abou kebeir': 'Abou kebeir',
    'tukh': 'Tukh',
    'el bab el gadid': 'El bab el gadid',
    'el montazah': 'El montazah',
    'el gamaleya': 'El gamaleya',
    '10th of ramadan': '10th of ramadan',
    'sekala': 'Sekala',
    'el mahata el gedidah': 'El mahata el gedidah',
    'abou kir': 'Abou kir',
    'el darrasa': 'El darrasa',
    'victoria': 'Victoria',
    'tanta': 'Tanta',
    'boulak': 'Boulak',
    'shoubra el khaymah': 'Shoubra el khaymah',
    'araisheyat misr': 'Araisheyat misr',
    'el fashn': 'El fashn',
    'hannoville': 'Hannoville',
    'ezbet el nakhl': 'Ezbet el nakhl',
    'dikirnis': 'Dikirnis',
    'karmouz': 'Karmouz',
    'shark district': 'Shark district',
    'talkha': 'Talkha',
    'mostafa kamel': 'Mostafa kamel',
    'aghakhan': 'Aghakhan',
    'tura': 'Tura',
    'al huseineya': 'Al huseineya',
    'villages rd.': 'Villages rd.',
    'kafr sakr': 'Kafr sakr',
    'el sabteya': 'El sabteya',
    'el marg': 'El marg',
    'el maasara': 'El maasara',
    'nasr city': 'Nasr city',
    'saray el koba': 'Saray el koba',
    'kebaa city': 'Kebaa city',
    'agami': 'Agami',
    'el haram': 'El haram',
    '6th of october': '6th of october',
    'el katameya': 'El katameya',
    'umm el sid hill': 'Umm el sid hill',
    'el sheikh zayed': 'El sheikh zayed',
    'road el farag': 'Road el farag',
    'sidi gaber': 'Sidi gaber',
    'ain shams el sharkeya': 'Ain shams el sharkeya',
    'shoubrakhit': 'Shoubrakhit',
    'geziret el dahab': 'Geziret el dahab',
    'port fouad': 'Port fouad',
    'el sayeda zeinab': 'El sayeda zeinab',
    'hadayek el kobba': 'Hadayek el kobba',
    'el hadara kebly': 'El hadara kebly',
    'el mandara': 'El mandara',
    'bahteem': 'Bahteem',
    'madinty': 'Madinty',
    'el marg el gadida': 'El marg el gadida',
    'pasha bay': 'Pasha bay',
    'mansheyet nasser': 'Mansheyet nasser',
    'kotsika': 'Kotsika',
    'el warak': 'El warak',
    'el hadkah': 'El hadkah',
    'deshna': 'Deshna',
    'qalyub': 'Qalyub',
    'downtown': 'Downtown',
    'qantarah gharb': 'Qantarah gharb',
    'gesr el suez': 'Gesr el suez',
    'belqas': 'Belqas',
    'zefta': 'Zefta',
    'el asafra': 'El asafra',
    'kafr shoukr': 'Kafr shoukr',
    'glim': 'Glim',
    'marina': 'Marina',
    'el hadaba': 'El hadaba',
    'kafr el elw': 'Kafr el elw',
    'ad dilinjat': 'Ad dilinjat',
    'el zohour district': 'El zohour district',
    'shebein el kanater': 'Shebein el kanater',
    'samannoud': 'Samannoud',
    'industrial zone': 'Industrial zone',
    'awlad saqr': 'Awlad saqr',
    'loran': 'Loran',
    'el zagazig': 'El zagazig',
    'new cairo': 'New cairo',
    'kafr el zayat': 'Kafr el zayat',
    'sayeda aisha': 'Sayeda aisha',
    "shark's bay": "Shark's bay",
    'el kawther': 'El kawther',
    'el ibrahimeya': 'El ibrahimeya',
    'kafr abdou': 'Kafr abdou',
    'el saraya': 'El saraya',
    'meniet el nasr': 'Meniet el nasr',
    'boulak el dakrour': 'Boulak el dakrour',
    'belbeis': 'Belbeis',
    'heliopolis': 'Heliopolis',
    'beilla': 'Beilla',
    'damanhour': 'Damanhour',
    'el riyad': 'El riyad',
    'imbaba': 'Imbaba',
    'el souk el kadim': 'El souk el kadim',
    'arish': 'Arish',
    'badr city': 'Badr city',
    'el hamoul': 'El hamoul',
    'ashmoun': 'Ashmoun',
    'mit ghamr': 'Mit ghamr',
    'el bagour': 'El bagour',
    'bab el louk': 'Bab el louk',
    'el manzalah': 'El manzalah',
    'el massalah': 'El massalah',
    'al kit kat': 'Al kit kat',
    'bab el shaareya': 'Bab el shaareya',
    'bassioun': 'Bassioun',
    'el shohadaa': 'El shohadaa',
    'as sinbillawain': 'As sinbillawain',
    'kerdasa': 'Kerdasa',
    'ain shams el gharbeya': 'Ain shams el gharbeya',
    'auseem': 'Auseem',
    'el darb el ahmar': 'El darb el ahmar',
    'el matareya': 'El matareya',
    'abou tig marina': 'Abou tig marina',
    'el khosous': 'El khosous',
    'manial el roda': 'Manial el roda',
    'el bitash': 'El bitash',
    'ganaklis': 'Ganaklis',
    'shoubra': 'Shoubra',
    'el manyal': 'El manyal',
    'minya el qamh': 'Minya el qamh',
    'kobry el koba': 'Kobry el koba',
    'manshyet el qanatir': 'Manshyet el qanatir',
    'aga': 'Aga',
    'ain shams': 'Ain shams',
    'el khanka': 'El khanka',
    'el hawamdeya': 'El hawamdeya',
    'el badrashin': 'El badrashin',
    'el sakakiny': 'El sakakiny',
    'helmeyet el zaitoun': 'Helmeyet el zaitoun',
    'el qanatir el khayriyah': 'El qanatir el khayriyah',
    'el zaytoun': 'El zaytoun',
    'el mandara el bahareya': 'El mandara el bahareya',
    'sherbin': 'Sherbin',
    'nagaa hamady': 'Nagaa hamady',
    'schutz': 'Schutz',
    'el mansheya': 'El mansheya',
    'maadi': 'Maadi',
    'el baragil': 'El baragil',
    'dahar': 'Dahar',
    'raml station': 'Raml station',
    'azarita': 'Azarita',
    'el afrang district': 'El afrang district',
    'tharwat': 'Tharwat',
    'hadayek el zaitoun': 'Hadayek el zaitoun',
    'wardeyan': 'Wardeyan',
    'bab shark': 'Bab shark',
    'el moneeb': 'El moneeb',
    'hadayek helwan': 'Hadayek helwan',
    'new damietta': 'New damietta',
    'el ayat': 'El ayat',
    'el asafra kebly': 'El asafra kebly',
    'hehia': 'Hehia',
    'el salam district': 'El salam district',
    'berket el sabaa': 'Berket el sabaa',
    'agouza': 'Agouza',
    'mohandeseen': 'Mohandeseen',
    'kom hamada': 'Kom hamada',
    'el waqf': 'El waqf',
    'zezenia': 'Zezenia',
    'miami': 'Miami',
    'amreya': 'Amreya',
    'bolkeley': 'Bolkeley',
    'kaleen': 'Kaleen',
    'mounira': 'Mounira',
    'obour city': 'Obour city',
    'zamalek': 'Zamalek',
    'helwan': 'Helwan',
}
