cities = {
    'el_beheira': 'El beheira',
    'kaliobeya': 'Kaliobeya',
    'north_sinai': 'North sinai',
    'alexandria': 'Alexandria',
    'port_said': 'Port said',
    'sharm_el_sheikh': 'Sharm el sheikh',
    'ismaileya': 'Ismaileya',
    'giza': 'Giza',
    'hurghada': 'Hurghada',
    'el_monofeya': 'El monofeya',
    'luxor': 'Luxor',
    'qena': 'Qena',
    'aswan': 'Aswan',
    'benisuef': 'Benisuef',
    'north_coast': 'North coast',
    'damietta': 'Damietta',
    'el_gouna': 'El gouna',
    'cairo': 'Cairo',
    'kafr_el_sheikh': 'Kafr el sheikh',
    'el_sharkeya': 'El sharkeya',
    'el_menia': 'El menia',
    'el_dakahleya': 'El dakahleya',
    'el_gharbeya': 'El gharbeya',
    'assyout': 'Assyout',
    'suez': 'Suez',
    'el_fayoum': 'El fayoum',
}


districts = {
    'el_manyal': 'El manyal',
    'kebaa_city': 'Kebaa city',
    'wardeyan': 'Wardeyan',
    'hannoville': 'Hannoville',
    'ezbet_el_nakhl': 'Ezbet el nakhl',
    'el_salam_city': 'El salam city',
    'abou_el_nomrous': 'Abou el nomrous',
    'boulak_el_dakrour': 'Boulak el dakrour',
    'kaha': 'Kaha',
    'mansheyet_nasser': 'Mansheyet nasser',
    'bigam': 'Bigam',
    'banha': 'Banha',
    'karmouz': 'Karmouz',
    'faggala': 'Faggala',
    'el_kawther': 'El kawther',
    'el_montazah': 'El montazah',
    'el_hawamdeya': 'El hawamdeya',
    'ain_shams': 'Ain shams',
    'abi_al_abbas': 'Abi al abbas',
    'kafr_sakr': 'Kafr sakr',
    'wadi_houf': 'Wadi houf',
    'geziret_el_dahab': 'Geziret el dahab',
    'tura': 'Tura',
    'alex._matrouh_desert_rd.': 'Alex. matrouh desert rd.',
    'el_moneeb': 'El moneeb',
    'alex._cairo_desert_rd.': 'Alex. cairo desert rd.',
    'al_huseineya': 'Al huseineya',
    'el_zagazig': 'El zagazig',
    'el_fustat': 'El fustat',
    'el_mandara': 'El mandara',
    'ramlet_boulak': 'Ramlet boulak',
    'el_saraya': 'El saraya',
    'mounira': 'Mounira',
    'el_hadkah': 'El hadkah',
    'el_shohadaa': 'El shohadaa',
    'minuf': 'Minuf',
    'el_bitash': 'El bitash',
    'al_kit_kat': 'Al kit kat',
    'abou_rawash': 'Abou rawash',
    'cleopatra': 'Cleopatra',
    'hamamat_el_kobba': 'Hamamat el kobba',
    'el_gomrok': 'El gomrok',
    'schutz': 'Schutz',
    'victoria': 'Victoria',
    'miami': 'Miami',
    'zamalek': 'Zamalek',
    'road_el_farag': 'Road el farag',
    'assyout': 'Assyout',
    'el_qanatir_el_khayriyah': 'El qanatir el khayriyah',
    'auseem': 'Auseem',
    'amreya': 'Amreya',
    'ain_shams_el_gharbeya': 'Ain shams el gharbeya',
    'deshna': 'Deshna',
    'nasr_city': 'Nasr city',
    'camp_shizar': 'Camp shizar',
    'el_zawia_el_hamra': 'El zawia el hamra',
    'sekala': 'Sekala',
    'etay_el_barod': 'Etay el barod',
    'el_saah_square': 'El saah square',
    'aghakhan': 'Aghakhan',
    'wabour_el_mayah': 'Wabour el mayah',
    'tharwat': 'Tharwat',
    'ghebrial': 'Ghebrial',
    'mallawi': 'Mallawi',
    'arish': 'Arish',
    'mit_ghamr': 'Mit ghamr',
    'ain_shams_el_sharkeya': 'Ain shams el sharkeya',
    'el_mahata_el_gedidah': 'El mahata el gedidah',
    'kutour': 'Kutour',
    'shebein_el_kawm': 'Shebein el kawm',
    'dikirnis': 'Dikirnis',
    'ashmoun': 'Ashmoun',
    'araisheyat_misr': 'Araisheyat misr',
    'el_waqf': 'El waqf',
    'giza': 'Giza',
    'el_badrashin': 'El badrashin',
    'mostafa_kamel': 'Mostafa kamel',
    'el_matareya': 'El matareya',
    'kafr_abdou': 'Kafr abdou',
    'wayli': 'Wayli',
    'el_salam_district': 'El salam district',
    'al_rehab_city': 'Al rehab city',
    "shark's_bay": "Shark's bay",
    'downtown': 'Downtown',
    'el_warak': 'El warak',
    'port_fouad': 'Port fouad',
    'sidi_beshr_bahary': 'Sidi beshr bahary',
    'el_sherouk_city': 'El sherouk city',
    'cairo_alex_desert_rd.': 'Cairo alex desert rd.',
    'shebein_el_kanater': 'Shebein el kanater',
    'bab_el_shaareya': 'Bab el shaareya',
    'el_ayat': 'El ayat',
    'el_khanka': 'El khanka',
    '10th_of_ramadan': '10th of ramadan',
    'industrial_zone': 'Industrial zone',
    'damanhour': 'Damanhour',
    'luxor': 'Luxor',
    'el_massalah': 'El massalah',
    'bolkeley': 'Bolkeley',
    'meniet_el_nasr': 'Meniet el nasr',
    'moharram_bey': 'Moharram bey',
    'el_bassateen': 'El bassateen',
    'el_gamaleya': 'El gamaleya',
    'dar_el_salam': 'Dar el salam',
    'beilla': 'Beilla',
    'bab_shark': 'Bab shark',
    'qalyub': 'Qalyub',
    'disuq': 'Disuq',
    'sidi_beshr': 'Sidi beshr',
    'sidi_beshr_kebly': 'Sidi beshr kebly',
    'el_marg': 'El marg',
    'abou_kebeir': 'Abou kebeir',
    'as-santah': 'As-santah',
    'el_mahalla_el_kobra': 'El mahalla el kobra',
    'marina': 'Marina',
    'roushdy': 'Roushdy',
    'mohandeseen': 'Mohandeseen',
    'el_asafra': 'El asafra',
    'el_nozha_el_gadida': 'El nozha el gadida',
    'el_asafra_kebly': 'El asafra kebly',
    'el_hadara_el_gadida': 'El hadara el gadida',
    'el_arbeen': 'El arbeen',
    'takseem_2': 'Takseem 2',
    'bab_el_louk': 'Bab el louk',
    'shoubrakhit': 'Shoubrakhit',
    'manshyet_el_qanatir': 'Manshyet el qanatir',
    'el_riyad': 'El riyad',
    'el_attarin': 'El attarin',
    'kafr_el_zayat': 'Kafr el zayat',
    'abou_youssef': 'Abou youssef',
    'hadayek_el_kobba': 'Hadayek el kobba',
    'el_quseyah': 'El quseyah',
    'helmeyet_el_zaitoun': 'Helmeyet el zaitoun',
    'sidi_gaber': 'Sidi gaber',
    'el_mansheya': 'El mansheya',
    'gharb_district': 'Gharb district',
    'banha_el_gadida': 'Banha el gadida',
    'el_manzalah': 'El manzalah',
    'el_nemsa': 'El nemsa',
    'ibshaway': 'Ibshaway',
    'abbasseya': 'Abbasseya',
    'new_damietta': 'New damietta',
    'helwan': 'Helwan',
    'kaleen': 'Kaleen',
    'misr_el_kadima': 'Misr el kadima',
    'el_koba_el_gadida': 'El koba el gadida',
    'el_asafra_bahary': 'El asafra bahary',
    'qantarah_gharb': 'Qantarah gharb',
    'ard_el_lewaa': 'Ard el lewaa',
    'el_khosous': 'El khosous',
    'loran': 'Loran',
    'el_hadara_kebly': 'El hadara kebly',
    'badr_city': 'Badr city',
    'aga': 'Aga',
    'ganaklis': 'Ganaklis',
    'imbaba': 'Imbaba',
    'dokki': 'Dokki',
    'el_mandara_el_bahareya': 'El mandara el bahareya',
    'el_baragil': 'El baragil',
    'umm_el_sid_hill': 'Umm el sid hill',
    'samannoud': 'Samannoud',
    'nagaa_hamady': 'Nagaa hamady',
    'el_marg_el_gadida': 'El marg el gadida',
    'san_stefano': 'San stefano',
    'saba_pasha': 'Saba pasha',
    'obour_city': 'Obour city',
    'el_ibrahimeya': 'El ibrahimeya',
    'dahar': 'Dahar',
    'benisuef': 'Benisuef',
    'el_sakakiny': 'El sakakiny',
    'garden_bay': 'Garden bay',
    'el_shark_district': 'El shark district',
    'maadi': 'Maadi',
    'hehia': 'Hehia',
    'hadayek_helwan': 'Hadayek helwan',
    'el_herafeyeen': 'El herafeyeen',
    'minya_el_qamh': 'Minya el qamh',
    'kafr_shoukr': 'Kafr shoukr',
    'cleopatra_al_mahata': 'Cleopatra al mahata',
    'as_sinbillawain': 'As sinbillawain',
    'azarita': 'Azarita',
    'el_roda': 'El roda',
    'el_helmeya_el_gedidah': 'El helmeya el gedidah',
    'el_zaytoun': 'El zaytoun',
    'fleming': 'Fleming',
    'el_afrang_district': 'El afrang district',
    'zefta': 'Zefta',
    'manial_el_roda': 'Manial el roda',
    'el_katameya': 'El katameya',
    'el_maasara': 'El maasara',
    'mokattam': 'Mokattam',
    'el_bagour': 'El bagour',
    'abou_kir': 'Abou kir',
    'sidi_abdel_rahman': 'Sidi abdel rahman',
    'hadayek_el_zaitoun': 'Hadayek el zaitoun',
    'el_bab_el_gadid': 'El bab el gadid',
    'el_sofy': 'El sofy',
    'saray_el_koba': 'Saray el koba',
    'el_sabteya': 'El sabteya',
    'lazoughly': 'Lazoughly',
    'el_mansoura': 'El mansoura',
    'gesr_el_suez': 'Gesr el suez',
    'garden_city': 'Garden city',
    'el_hamoul': 'El hamoul',
    'bahteem': 'Bahteem',
    'el_amireya': 'El amireya',
    'villages_rd.': 'Villages rd.',
    'el_haram': 'El haram',
    'el_souk_el_kadim': 'El souk el kadim',
    'raml_station': 'Raml station',
    'naama_bay': 'Naama bay',
    'glim': 'Glim',
    'belbeis': 'Belbeis',
    'el_darb_el_ahmar': 'El darb el ahmar',
    'sherbin': 'Sherbin',
    'sporting': 'Sporting',
    'madinty': 'Madinty',
    'kotsika': 'Kotsika',
    'berket_el_sabaa': 'Berket el sabaa',
    'el_zaher': 'El zaher',
    'suez_district': 'Suez district',
    'belqas': 'Belqas',
    'el_fashn': 'El fashn',
    'bein_el_sarayat': 'Bein el sarayat',
    'sayeda_aisha': 'Sayeda aisha',
    'heliopolis': 'Heliopolis',
    'pasha_bay': 'Pasha bay',
    'bahary': 'Bahary',
    'shoubra_el_khaymah': 'Shoubra el khaymah',
    'agouza': 'Agouza',
    'shark_district': 'Shark district',
    'boulak': 'Boulak',
    'awlad_saqr': 'Awlad saqr',
    'el_kalag': 'El kalag',
    'ad_dilinjat': 'Ad dilinjat',
    'dayr_mawas': 'Dayr mawas',
    'el_hadaba': 'El hadaba',
    'damietta': 'Damietta',
    'agami': 'Agami',
    'el_sawah': 'El sawah',
    'kafr_el_elw': 'Kafr el elw',
    'quwasnah': 'Quwasnah',
    'kerdasa': 'Kerdasa',
    'abou_zaabal': 'Abou zaabal',
    'shoubra': 'Shoubra',
    'el_seyouf_shamaa': 'El seyouf shamaa',
    'el_hadara': 'El hadara',
    'kobry_el_koba': 'Kobry el koba',
    '6th_of_october': '6th of october',
    'talkha': 'Talkha',
    'semouha': 'Semouha',
    'tukh': 'Tukh',
    'faisal': 'Faisal',
    'el_sheikh_zayed': 'El sheikh zayed',
    'esna': 'Esna',
    'abou_tig_marina': 'Abou tig marina',
    'zezenia': 'Zezenia',
    'el_sayeda_zeinab': 'El sayeda zeinab',
    'el_seyouf': 'El seyouf',
    'kom_hamada': 'Kom hamada',
    'bassioun': 'Bassioun',
    'new_cairo': 'New cairo',
    'el_darrasa': 'El darrasa',
    'abou_hammad': 'Abou hammad',
    'tanta': 'Tanta',
    'el_zohour_district': 'El zohour district',
}
